### ISSUE TITLE
NoMethodError-> undefined method `set' for Chef::Platform:Class

### ISSUE THREAD

**Issue by srajappa** [chef-cookbooks/git#119]
### Cookbook version
4.6.0

### Chef-client version
12.18.31
More Info:
```
$ chef --version
Chef Development Kit Version: 1.2.22
chef-client version: 12.18.31
delivery version: master (0b746cafed65a9ea1a79de3cc546e7922de9187c)
berks version: 2017-04-12T17:34:32.378170 15636] 2017-04-12T17:34:32.378671 15636] 2017-04-12T17:34:32.378671 15636] 2017-04-12T17:34:32.379172 15636] 2017-04-12T17:34:32.457883 15636] 2017-04-12T17:34:32.458383 15636] 5.6.0
kitchen version: 1.15.0
```

### Platform Details
_**For Kitchen**_
Driver: Vagrant
Platform: centos-7.2

### Scenario:
Need to have a Git client (default) for the target node. 
```
       NoMethodError
       -------------
       undefined method 'set' for Chef::Platform:Class

       Cookbook Trace:
       ---------------
         /tmp/kitchen/cache/cookbooks/git/libraries/z_provider_mapping.rb:6:in `<top (required)>'

```

### Steps to Reproduce:

1.  I am developing a cookbook that will install Jenkins. 
2. I am using Git Cookbook to install git client on the target node. 
3. The `'include_recipe "git::default"'` is called after creating the users (Jenkins) and some directories.
4. It was _**converging**_ without any issues earlier when I had this line in `metadata.rb` depends `'git', '~> 4.3'`.
5. Now, it doesn't seem to work and I am observing version 4.6.0 is used as verified in [Berksfile.lock](https://gist.github.com/srajappa/1583430771a5e50ac2cc491ee1e9b8c4).

### Expected Result:
Git Client should be installed! But instead I get this syntax error, saying 'set' is not found.

### Actual Result:

```
$ kitchen converge
-----> Starting Kitchen (v1.15.0)
W, [2017-04-12T17:09:51.956502 #8552]  WARN -- : You are setting a key that conflicts with a built-in method Hashie::Mash#frozen? defined in Kernel. This can cause unexpected behavior when accessing the key via as a property. You can still access the key via the #[] method.
W, [2017-04-12T17:09:51.956502 #8552]  WARN -- : You are setting a key that conflicts with a built-in method Hashie::Mash#frozen? defined in Kernel. This can cause unexpected behavior when accessing the key via as a property. You can still access the key via the #[] method.
W, [2017-04-12T17:09:51.957005 #8552]  WARN -- : You are setting a key that conflicts with a built-in method VariaModel::Attributes#frozen? defined in Kernel. This can cause unexpected behavior when accessing the key via as a property. You can still access the key via the #[] method.
W, [2017-04-12T17:09:51.957005 #8552]  WARN -- : You are setting a key that conflicts with a built-in method VariaModel::Attributes#frozen? defined in Kernel. This can cause unexpected behavior when accessing the key via as a property. You can still access the key via the #[] method.
W, [2017-04-12T17:09:51.967032 #8552]  WARN -- : You are setting a key that conflicts with a built-in method VariaModel::Attributes#default defined in Hash. This can cause unexpected behavior when accessing the key via as a property. You can still access the key via the #[] method.
W, [2017-04-12T17:09:51.967533 #8552]  WARN -- : You are setting a key that conflicts with a built-in method VariaModel::Attributes#default defined in Hash. This can cause unexpected behavior when accessing the key via as a property. You can still access the key via the #[] method.
-----> Converging <default-centos-72>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 5.6.0...
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
-----> Chef Omnibus installation detected (install only if missing)
       Transferring files to <default-centos-72>
       Starting Chef Client, version 13.0.118
       resolving cookbooks for run list: ["scm_jenkins::default"]
       Synchronizing Cookbooks:
         - scm_jenkins (0.1.0)
         - java (1.48.0)
         - git (4.6.0)
         - apt (6.0.1)
         - windows (3.0.5)
         - homebrew (3.0.0)
         - build-essential (8.0.0)
         - yum-epel (2.1.1)
         - ohai (5.0.3)
         - seven_zip (2.0.2)
         - mingw (2.0.0)
         - compat_resource (12.16.3)
         - dmg (3.1.0)
       Installing Cookbook Gems:
       Compiling Cookbooks...

       ================================================================================
       Recipe Compile Error in /tmp/kitchen/cache/cookbooks/git/libraries/z_provider_mapping.rb
       ================================================================================

       NoMethodError
       -------------
       undefined method `set' for Chef::Platform:Class

       Cookbook Trace:
       ---------------
         /tmp/kitchen/cache/cookbooks/git/libraries/z_provider_mapping.rb:6:in `<top (required)>'

       Relevant File Content:
       ----------------------
       /tmp/kitchen/cache/cookbooks/git/libraries/z_provider_mapping.rb:

         1:  # provider mappings for Chef 11
         2:
         3:  #########
         4:  # client
         5:  #########
         6>> Chef::Platform.set platform: :amazon, resource: :git_client, provider: Chef::Provider::GitClient::Package
         7:  Chef::Platform.set platform: :centos, resource: :git_client, provider: Chef::Provider::GitClient::Package
         8:  Chef::Platform.set platform: :debian, resource: :git_client, provider: Chef::Provider::GitClient::Package
         9:  Chef::Platform.set platform: :fedora, resource: :git_client, provider: Chef::Provider::GitClient::Package
        10:  Chef::Platform.set platform: :mac_os_x, resource: :git_client, provider: Chef::Provider::GitClient::Osx
        11:  Chef::Platform.set platform: :redhat, resource: :git_client, provider: Chef::Provider::GitClient::Package
        12:  Chef::Platform.set platform: :scientific, resource: :git_client, provider: Chef::Provider::GitClient::Package
        13:  Chef::Platform.set platform: :smartos, resource: :git_client, provider: Chef::Provider::GitClient::Package
        14:  Chef::Platform.set platform: :solaris2, resource: :git_client, provider: Chef::Provider::GitClient::Package
        15:  Chef::Platform.set platform: :suse, resource: :git_client, provider: Chef::Provider::GitClient::Package

       System Info:
       ------------
       chef_version=13.0.118
       platform=centos
       platform_version=7.2.1511
       ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
       program_name=chef-client worker: ppid=11846;start=00:10:07;
       executable=/opt/chef/bin/chef-client


       Running handlers:
       [2017-04-13T00:10:09+00:00] ERROR: Running exception handlers
       [2017-04-13T00:10:09+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2017-04-13T00:10:09+00:00] ERROR: Exception handlers complete
       [2017-04-13T00:10:09+00:00] ERROR: Exception handlers complete
       Chef Client failed. 0 resources updated in 01 seconds
       [2017-04-13T00:10:09+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2017-04-13T00:10:09+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2017-04-13T00:10:09+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2017-04-13T00:10:09+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2017-04-13T00:10:09+00:00] ERROR: undefined method `set' for Chef::Platform:Class
       [2017-04-13T00:10:09+00:00] ERROR: undefined method `set' for Chef::Platform:Class
       [2017-04-13T00:10:09+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
       [2017-04-13T00:10:09+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Converge failed on instance <default-centos-72>.  Please see .kitchen/logs/default-centos-72.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

**Comment by ilovemysillybanana** [comment]
I'm having this issue on 5.0.x as well.

**Comment by utaman1** [comment]
hi, @ilovemysillybanana. Could you please specify what you mean by Updating to 6.0.0, and how you did it. Thanks.

**Comment by dhanushrajendra** [comment]
Hi @ilovemysillybanana  can you please specify which version you updated?

**Comment by ilovemysillybanana** [comment]
Oh, terribly sorry. I should have been more clear. I was working on my own cookbook and I all did was replace the line in my metadata file.

From this:
```
depends 'git', '~> 5.0.0'
```

To this:
```
depends 'git', '~> 6.0.0'
```

And then ran `berks update` or `berks install` it should fetch the newest version of the cookbook for you, that solved the problem for me.

**Comment by tas50** [comment]
@srajappa You're actually running chef-client 13 from the looks of the run log. The 5.0 version of this cookbook isn't compatible with Chef 13. The 6.0 release resolves this issue. As @ilovemysillybanana mentioned you'll need to update your cookbook to use the latest release.

**Comment by nomadcoder87** [comment]
Same error, in Ubuntu+Postgres+Rails with Vagrant which installed successfully, i'm using a window 10 laptop without virtualization, after of a lot of pain i was able to make irtualbox works, but when i run "vagrant provision" it doesn't works.
