### ISSUE TITLE
STDERR: No provider of 'git=2.26.2-27.36.1' found.

### ISSUE THREAD

**Issue by Vazzilena** [chef-cookbooks/git#137]
Hey,

I am using the recipe and work wonderfully on our win/rhel/centos machines.

It fails however on suse. This is the console log from the execution of the command sudo chef-client -o 'recipe[git]'

[2020-07-17T15:05:53.153Z] Processing sofumsuse06.eur.ad.sag
[2020-07-17T15:05:54.364Z] Processing sofumsuse06.eur.ad.sag
[2020-07-17T15:05:54.639Z] + sudo chef-client -o 'recipe[git]'
[2020-07-17T15:06:02.764Z] Starting Chef Client, version 14.13.11[0m
[2020-07-17T15:06:12.701Z] [2020-07-17T17:52:34+03:00] WARN: Run List override has been provided.
[2020-07-17T15:06:12.701Z] [2020-07-17T17:52:34+03:00] WARN: Original Run List: []
[2020-07-17T15:06:12.701Z] [2020-07-17T17:52:34+03:00] WARN: Overridden Run List: [recipe[git]]
[2020-07-17T15:06:12.701Z] resolving cookbooks for run list: ["git"][0m
[2020-07-17T15:06:12.701Z] Synchronizing Cookbooks:[0m
[2020-07-17T15:06:12.701Z]   - git (10.0.0)[0m
[2020-07-17T15:06:12.701Z] Installing Cookbook Gems:[0m
[2020-07-17T15:06:12.701Z] Compiling Cookbooks...[0m
[2020-07-17T15:06:12.701Z] Converging 1 resources[0m
[2020-07-17T15:06:12.701Z] Recipe: git::package[0m
[2020-07-17T15:06:12.701Z]   * git_client[default] action install
[2020-07-17T15:06:19.228Z]     * zypper_package[default :create git] action install
[2020-07-17T15:06:19.228Z]       [0m
[2020-07-17T15:06:19.228Z]       ================================================================================[0m
[2020-07-17T15:06:19.228Z]       [31mError executing action `install` on resource 'zypper_package[default :create git]'[0m
[2020-07-17T15:06:19.228Z]       ================================================================================[0m
[2020-07-17T15:06:19.228Z]       
[2020-07-17T15:06:19.228Z] [0m      Mixlib::ShellOut::ShellCommandFailed[0m
[2020-07-17T15:06:19.228Z]       ------------------------------------[0m
[2020-07-17T15:06:19.228Z]       Expected process to exit with [0], but received '104'
[2020-07-17T15:06:19.228Z] [0m      ---- Begin output of ["zypper", "--non-interactive", "install", "--auto-agree-with-licenses", "git=2.26.2-27.36.1"] ----
[2020-07-17T15:06:19.228Z] [0m      STDOUT: Refreshing service 'SUSE_Linux_Enterprise_Server_12_SP4_x86_64'.
[2020-07-17T15:06:19.228Z] [0m      Loading repository data...
[2020-07-17T15:06:19.228Z] [0m      Reading installed packages...
[2020-07-17T15:06:19.228Z] [0m      'git=2.26.2-27.36.1' not found in package names. Trying capabilities.
[2020-07-17T15:06:19.228Z] [0m      STDERR: No provider of 'git=2.26.2-27.36.1' found.
[2020-07-17T15:06:19.228Z] [0m      ---- End output of ["zypper", "--non-interactive", "install", "--auto-agree-with-licenses", "git=2.26.2-27.36.1"] ----
[2020-07-17T15:06:19.228Z] [0m      Ran ["zypper", "--non-interactive", "install", "--auto-agree-with-licenses", "git=2.26.2-27.36.1"] returned 104[0m
[2020-07-17T15:06:19.228Z]       
[2020-07-17T15:06:19.228Z] [0m      Resource Declaration:[0m
[2020-07-17T15:06:19.228Z]       ---------------------[0m
[2020-07-17T15:06:19.228Z]       # In /var/chef/cache/cookbooks/git/libraries/provider_git_client_package.rb
[2020-07-17T15:06:19.228Z] [0m      
[2020-07-17T15:06:19.228Z] [0m        9:           package "#{new_resource.name} :create #{parsed_package_name}" do
[2020-07-17T15:06:19.228Z] [0m       10:             package_name parsed_package_name
[2020-07-17T15:06:19.228Z] [0m       11:             version parsed_package_version
[2020-07-17T15:06:19.228Z] [0m       12:             action new_resource.package_action
[2020-07-17T15:06:19.228Z] [0m       13:             action :install
[2020-07-17T15:06:19.228Z] [0m       14:           end
[2020-07-17T15:06:19.228Z] [0m       15:         end
[2020-07-17T15:06:19.228Z] [0m      
[2020-07-17T15:06:19.228Z] [0m      Compiled Resource:[0m
[2020-07-17T15:06:19.228Z]       ------------------[0m
[2020-07-17T15:06:19.228Z]       # Declared in /var/chef/cache/cookbooks/git/libraries/provider_git_client_package.rb:9:in `block in <class:Package>'
[2020-07-17T15:06:19.228Z] [0m      
[2020-07-17T15:06:19.228Z] [0m      zypper_package("default :create git") do
[2020-07-17T15:06:19.228Z] [0m        package_name "git"
[2020-07-17T15:06:19.228Z] [0m        action [:install]
[2020-07-17T15:06:19.228Z] [0m        default_guard_interpreter :default
[2020-07-17T15:06:19.228Z] [0m        declared_type :package
[2020-07-17T15:06:19.228Z] [0m        cookbook_name "git"
[2020-07-17T15:06:19.228Z] [0m        version nil
[2020-07-17T15:06:19.228Z] [0m      end
[2020-07-17T15:06:19.228Z] [0m      
[2020-07-17T15:06:19.228Z] [0m      System Info:[0m
[2020-07-17T15:06:19.228Z]       ------------[0m
[2020-07-17T15:06:19.228Z]       chef_version=14.13.11
[2020-07-17T15:06:19.228Z] [0m      platform=suse
[2020-07-17T15:06:19.228Z] [0m      platform_version=12.4
[2020-07-17T15:06:19.228Z] [0m      ruby=ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux]
[2020-07-17T15:06:19.228Z] [0m      program_name=/usr/bin/chef-client
[2020-07-17T15:06:19.228Z] [0m      executable=/opt/chef/bin/chef-client[0m
[2020-07-17T15:06:19.228Z]       
[2020-07-17T15:06:19.228Z] [0m    [0m
[2020-07-17T15:06:19.228Z]     ================================================================================[0m
[2020-07-17T15:06:19.228Z]     [31mError executing action `install` on resource 'git_client[default]'[0m
[2020-07-17T15:06:19.228Z]     ================================================================================[0m
[2020-07-17T15:06:19.228Z]     
[2020-07-17T15:06:19.228Z] [0m    Mixlib::ShellOut::ShellCommandFailed[0m
[2020-07-17T15:06:19.228Z]     ------------------------------------[0m
[2020-07-17T15:06:19.228Z]     zypper_package[default :create git] (/var/chef/cache/cookbooks/git/libraries/provider_git_client_package.rb line 9) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '104'
[2020-07-17T15:06:19.228Z] [0m    ---- Begin output of ["zypper", "--non-interactive", "install", "--auto-agree-with-licenses", "git=2.26.2-27.36.1"] ----
[2020-07-17T15:06:19.228Z] [0m    STDOUT: Refreshing service 'SUSE_Linux_Enterprise_Server_12_SP4_x86_64'.
[2020-07-17T15:06:19.228Z] [0m    Loading repository data...
[2020-07-17T15:06:19.228Z] [0m    Reading installed packages...
[2020-07-17T15:06:19.228Z] [0m    'git=2.26.2-27.36.1' not found in package names. Trying capabilities.
[2020-07-17T15:06:19.228Z] [0m    STDERR: No provider of 'git=2.26.2-27.36.1' found.
[2020-07-17T15:06:19.228Z] [0m    ---- End output of ["zypper", "--non-interactive", "install", "--auto-agree-with-licenses", "git=2.26.2-27.36.1"] ----
[2020-07-17T15:06:19.228Z] [0m    Ran ["zypper", "--non-interactive", "install", "--auto-agree-with-licenses", "git=2.26.2-27.36.1"] returned 104[0m
[2020-07-17T15:06:19.228Z]     
[2020-07-17T15:06:19.228Z] [0m    Resource Declaration:[0m
[2020-07-17T15:06:19.228Z]     ---------------------[0m
[2020-07-17T15:06:19.228Z]     # In /var/chef/cache/cookbooks/git/recipes/package.rb
[2020-07-17T15:06:19.228Z] [0m    
[2020-07-17T15:06:19.228Z] [0m     23:   git_client 'default' do
[2020-07-17T15:06:19.228Z] [0m     24:     action :install
[2020-07-17T15:06:19.228Z] [0m     25:   end
[2020-07-17T15:06:19.229Z] [0m     26: end
[2020-07-17T15:06:19.229Z] [0m    
[2020-07-17T15:06:19.229Z] [0m    Compiled Resource:[0m
[2020-07-17T15:06:19.229Z]     ------------------[0m
[2020-07-17T15:06:19.229Z]     # Declared in /var/chef/cache/cookbooks/git/recipes/package.rb:23:in `from_file'
[2020-07-17T15:06:19.229Z] [0m    
[2020-07-17T15:06:19.229Z] [0m    git_client("default") do
[2020-07-17T15:06:19.229Z] [0m      action [:install]
[2020-07-17T15:06:19.229Z] [0m      default_guard_interpreter :default
[2020-07-17T15:06:19.229Z] [0m      declared_type :git_client
[2020-07-17T15:06:19.229Z] [0m      cookbook_name "git"
[2020-07-17T15:06:19.229Z] [0m      recipe_name "package"
[2020-07-17T15:06:19.229Z] [0m    end
[2020-07-17T15:06:19.229Z] [0m    
[2020-07-17T15:06:19.229Z] [0m    System Info:[0m
[2020-07-17T15:06:19.229Z]     ------------[0m
[2020-07-17T15:06:19.229Z]     chef_version=14.13.11
[2020-07-17T15:06:19.229Z] [0m    platform=suse
[2020-07-17T15:06:19.229Z] [0m    platform_version=12.4
[2020-07-17T15:06:19.229Z] [0m    ruby=ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux]
[2020-07-17T15:06:19.229Z] [0m    program_name=/usr/bin/chef-client
[2020-07-17T15:06:19.229Z] [0m    executable=/opt/chef/bin/chef-client[0m
[2020-07-17T15:06:19.229Z]     
[2020-07-17T15:06:19.229Z] [0m[0m
[2020-07-17T15:06:19.229Z] Running handlers:[0m
[2020-07-17T15:06:19.229Z] [2020-07-17T17:52:40+03:00] ERROR: Running exception handlers
[2020-07-17T15:06:19.229Z] Running handlers complete
[2020-07-17T15:06:19.229Z] [0m[2020-07-17T17:52:40+03:00] ERROR: Exception handlers complete
[2020-07-17T15:06:19.229Z] Chef Client failed. 0 resources updated in 16 seconds[0m
[2020-07-17T15:06:19.229Z] [2020-07-17T17:52:40+03:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2020-07-17T15:06:19.229Z] [2020-07-17T17:52:40+03:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2020-07-17T15:06:19.229Z] [2020-07-17T17:52:40+03:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: git_client[default] (git::package line 23) had an error: Mixlib::ShellOut::ShellCommandFailed: zypper_package[default :create git] (/var/chef/cache/cookbooks/git/libraries/provider_git_client_package.rb line 9) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '104'
[2020-07-17T15:06:19.229Z] ---- Begin output of ["zypper", "--non-interactive", "install", "--auto-agree-with-licenses", "git=2.26.2-27.36.1"] ----
[2020-07-17T15:06:19.229Z] STDOUT: Refreshing service 'SUSE_Linux_Enterprise_Server_12_SP4_x86_64'.
[2020-07-17T15:06:19.229Z] Loading repository data...
[2020-07-17T15:06:19.229Z] Reading installed packages...
[2020-07-17T15:06:19.229Z] 'git=2.26.2-27.36.1' not found in package names. Trying capabilities.
[2020-07-17T15:06:19.229Z] STDERR: No provider of 'git=2.26.2-27.36.1' found.
[2020-07-17T15:06:19.229Z] ---- End output of ["zypper", "--non-interactive", "install", "--auto-agree-with-licenses", "git=2.26.2-27.36.1"] ----
[2020-07-17T15:06:19.229Z] Ran ["zypper", "--non-interactive", "install", "--auto-agree-with-licenses", "git=2.26.2-27.36.1"] returned 104
script returned exit code 1

Chef stacktrace file:

vmtest@sofumsuse06:~> sudo cat /var/chef/cache/chef-stacktrace.out
Generated at 2020-07-17 17:52:40 +0300
Mixlib::ShellOut::ShellCommandFailed: git_client[default] (git::package line 23)                                                                                                                                                              had an error: Mixlib::ShellOut::ShellCommandFailed: zypper_package[default :cre                                                                                                                                                             ate git] (/var/chef/cache/cookbooks/git/libraries/provider_git_client_package.rb                                                                                                                                                              line 9) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to                                                                                                                                                              exit with [0], but received '104'
---- Begin output of ["zypper", "--non-interactive", "install", "--auto-agree-wi                                                                                                                                                             th-licenses", "git=2.26.2-27.36.1"] ----
STDOUT: Refreshing service 'SUSE_Linux_Enterprise_Server_12_SP4_x86_64'.
Loading repository data...
Reading installed packages...
'git=2.26.2-27.36.1' not found in package names. Trying capabilities.
STDERR: No provider of 'git=2.26.2-27.36.1' found.
---- End output of ["zypper", "--non-interactive", "install", "--auto-agree-with                                                                                                                                                             -licenses", "git=2.26.2-27.36.1"] ----
Ran ["zypper", "--non-interactive", "install", "--auto-agree-with-licenses", "gi                                                                                                                                                             t=2.26.2-27.36.1"] returned 104
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/mixlib-shellout-2.4.4/lib/mixlib/she                                                                                                                                                             llout.rb:297:in `invalid!'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/mixlib-shellout-2.4.4/lib/mixlib/she                                                                                                                                                             llout.rb:284:in `error!'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/mixin/shell_o                                                                                                                                                             ut.rb:202:in `shell_out_compacted!'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/mixin/shell_o                                                                                                                                                             ut.rb:124:in `shell_out!'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/provider/pack                                                                                                                                                             age/zypper.rb:149:in `zypper_package'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/provider/pack                                                                                                                                                             age/zypper.rb:112:in `install_package'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/provider/pack                                                                                                                                                             age.rb:102:in `block (3 levels) in <class:Package>'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/provider/pack                                                                                                                                                             age.rb:269:in `multipackage_api_adapter'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/provider/pack                                                                                                                                                             age.rb:101:in `block (2 levels) in <class:Package>'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/mixin/why_run                                                                                                                                                             .rb:51:in `add_action'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/provider.rb:2                                                                                                                                                             27:in `converge_by'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/provider/pack                                                                                                                                                             age.rb:100:in `block in <class:Package>'
(eval):2:in `block in action_install'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/provider.rb:2                                                                                                                                                             36:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/provider.rb:2                                                                                                                                                             36:in `compile_and_converge_action'
(eval):2:in `action_install'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/provider.rb:1                                                                                                                                                             82:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/resource.rb:5                                                                                                                                                             78:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/runner.rb:70:                                                                                                                                                             in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/runner.rb:98:                                                                                                                                                             in `block (2 levels) in converge'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/runner.rb:98:                                                                                                                                                             in `each'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/runner.rb:98:                                                                                                                                                             in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/resource_coll                                                                                                                                                             ection/resource_list.rb:94:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/resource_coll                                                                                                                                                             ection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/resource_coll                                                                                                                                                             ection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/resource_coll                                                                                                                                                             ection/stepable_iterator.rb:103:in `iterate'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/resource_coll                                                                                                                                                             ection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/resource_coll                                                                                                                                                             ection/resource_list.rb:92:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/runner.rb:97:                                                                                                                                                             in `converge'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/provider.rb:2                                                                                                                                                             37:in `compile_and_converge_action'
(eval):2:in `action_install'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/provider.rb:1                                                                                                                                                             82:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/resource.rb:5                                                                                                                                                             78:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/runner.rb:70:                                                                                                                                                             in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/runner.rb:98:                                                                                                                                                             in `block (2 levels) in converge'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/runner.rb:98:                                                                                                                                                             in `each'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/runner.rb:98:                                                                                                                                                             in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/resource_coll                                                                                                                                                             ection/resource_list.rb:94:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/resource_coll                                                                                                                                                             ection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/resource_coll                                                                                                                                                             ection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/resource_coll                                                                                                                                                             ection/stepable_iterator.rb:103:in `iterate'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/resource_coll                                                                                                                                                             ection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/resource_coll                                                                                                                                                             ection/resource_list.rb:92:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/runner.rb:97:                                                                                                                                                             in `converge'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/client.rb:720                                                                                                                                                             :in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/client.rb:715                                                                                                                                                             :in `catch'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/client.rb:715                                                                                                                                                             :in `converge'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/client.rb:754                                                                                                                                                             :in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/client.rb:286                                                                                                                                                             :in `run'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/application.r                                                                                                                                                             b:303:in `run_with_graceful_exit_option'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/application.r                                                                                                                                                             b:279:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/local_mode.rb                                                                                                                                                             :44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/application.r                                                                                                                                                             b:261:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/application/c                                                                                                                                                             lient.rb:449:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/application.r                                                                                                                                                             b:66:in `run'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/bin/chef-client:25:in                                                                                                                                                              `<top (required)>'
/usr/bin/chef-client:81:in `load'
/usr/bin/chef-client:81:in `<main>'vmtest@sofumsuse06:~>

Vers
[chef-stacktrace.log](https://github.com/chef-cookbooks/git/files/4939113/chef-stacktrace.log)
[console.log](https://github.com/chef-cookbooks/git/files/4939114/console.log)

ion of the suse machine:

vmtest@sofumsuse06:~> cat /etc/*release*
NAME="SLES"
VERSION="12-SP4"
VERSION_ID="12.4"
PRETTY_NAME="SUSE Linux Enterprise Server 12 SP4"
ID="sles"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:12:sp4"
SUSE Linux Enterprise Server 12 (x86_64)
VERSION = 12
PATCHLEVEL = 4
# This file is deprecated and will be removed in a future service pack or release.
# Please check /etc/os-release for details about this release.

**Comment by thirumoorthir** [comment]
Hi @Vazzilena I think this cookbook is not support “SUSE_Linux_Enterprise_Server_12_SP4_x86_64”, Please note the support platforms 
```
|---------------+-------|
| amazonlinux-2 | X     |
|---------------+-------|
| centos-7      | X     |
|---------------+-------|
| centos-8      | X     |
|---------------+-------|
| fedora        | X     |
|---------------+-------|
| debian-9      | X     |
|---------------+-------|
| debian-10     | X     |
|---------------+-------|
| ubuntu-16.04  | X     |
|---------------+-------|
| ubuntu-18.04  | X     |
|---------------+-------|
| ubuntu-20.04  | X     |
|---------------+-------|
| openSUSE Leap | X     |
|---------------+-------|
```

**Comment by thirumoorthir** [comment]
@ramereth  are we supporting Suse Enterprise Linux or it is out of scope ?

**Comment by ramereth** [comment]
We try to support at least OpenSUSE Leap 15 since that's easy for us to test against.
